repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: check-json
  - id: check-yaml
  - id: check-merge-conflict
  - id: check-toml
  - id: end-of-file-fixer
  - id: mixed-line-ending
- repo: https://github.com/doublify/pre-commit-rust
  rev: v1.0
  hooks:
  - id: fmt
    args: ['--manifest-path', 'box_world/Cargo.toml', '--verbose', '--']
  - id: clippy
    args: ['--manifest-path', 'box_world/Cargo.toml']
  - id: fmt
    args: ['--manifest-path', 'box_world_data/Cargo.toml', '--verbose', '--']
  - id: clippy
    args: ['--manifest-path', 'box_world_data/Cargo.toml']
